#!/usr/bin/env bash
# Behavioral tests for the authoritative commit-msg hook at
# git/hooks/commit-msg. This is the single gate for commit messages
# and catches every input shape: -m, -F, --file, -t, heredoc, editor.
# There is intentionally no PreToolUse agent-hook equivalent (see
# docs/agentic-tooling.md for the rationale).
#
# Strategy: invoke the hook directly with a temp message file (the
# same way git invokes it). No real `git commit` needed -- we just
# need to confirm the hook's decision on each message shape.

set +e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOK="$DOTFILES_DIR/git/hooks/commit-msg"

source "$SCRIPT_DIR/test-framework.sh"

# Run the commit-msg hook against a message string. Returns "accepted"
# (exit 0) or "rejected" (non-zero). The hook reads a file, so we
# stage the message in a tempfile per invocation.
run_msg() {
    local msg="$1"
    local tmp
    tmp=$(mktemp)
    printf '%s\n' "$msg" > "$tmp"
    # Clear the recursion guard so re-running in one test session works.
    unset DOTFILES_GLOBAL_HOOK_RUNNING
    if bash "$HOOK" "$tmp" >/dev/null 2>&1; then
        echo "accepted"
    else
        echo "rejected"
    fi
    rm -f "$tmp"
}

assert_rejected() {
    local actual="$1"
    local message="$2"
    if [[ "$actual" == "rejected" ]]; then
        test_pass "$message"
    else
        test_fail "$message (expected rejected, got $actual)"
    fi
}

assert_accepted() {
    local actual="$1"
    local message="$2"
    if [[ "$actual" == "accepted" ]]; then
        test_pass "$message"
    else
        test_fail "$message (expected accepted, got $actual)"
    fi
}

# ---------------------------------------------------------------------------

test_suite "commit-msg: prerequisites"

bash -n "$HOOK" 2>/dev/null
assert_return_code 0 $? "commit-msg passes bash -n"
if [[ -x "$HOOK" ]]; then
    test_pass "commit-msg is executable"
else
    test_fail "commit-msg is executable"
fi

# ---------------------------------------------------------------------------

test_suite "commit-msg: input-shape coverage"

# commit-msg is the single gate for commit messages: git invokes it
# regardless of how the message was supplied (-m, -F, --file=, -t,
# heredoc, editor). These shapes all reach it uniformly because it
# reads the resolved message file after git has handled every input
# form.

# Heredoc with non-EOF marker.
heredoc_evil=$'feat: ok subject\n\nGenerated by Claude'
assert_rejected "$(run_msg "$heredoc_evil")" "Blocks attribution regardless of input shape (heredoc marker)"

# A message that would have arrived via `git commit -F /tmp/msg` is
# indistinguishable to commit-msg from any other source.
commit_F=$'fix: real fix\n\nCo-Authored-By: bot <b@x>'
assert_rejected "$(run_msg "$commit_F")" "Blocks co-author regardless of input shape (-F)"

# A message arriving from `git commit -t template` -- same story.
commit_t=$'wip\n\nedited from template'
assert_rejected "$(run_msg "$commit_t")" "Blocks non-conventional subject regardless of input shape (was: -t bypass)"

# ---------------------------------------------------------------------------

test_suite "commit-msg: AI attribution"

assert_rejected "$(run_msg "feat(auth): add login

Generated with Claude")" "Blocks 'Generated with Claude'"
assert_rejected "$(run_msg "fix: handle nulls

Co-Authored-By: Claude <noreply@anthropic.com>")" "Blocks Co-Authored-By"
assert_rejected "$(run_msg "feat: refactor

Created by Copilot")" "Blocks 'Created by Copilot'"
assert_rejected "$(run_msg "fix: oops

written with GPT")" "Blocks 'written with GPT'"
assert_rejected "$(run_msg "feat: new thing

claude.com/code review")" "Blocks claude.com URL"

# Bare tool names in technical context should pass.
assert_accepted "$(run_msg "fix(claude-code): handle empty input")" "Allows tool name in scope"
assert_accepted "$(run_msg "docs: update copilot integration notes")" "Allows tool name in body"

# ---------------------------------------------------------------------------

test_suite "commit-msg: conventional format"

assert_accepted "$(run_msg "feat: add user login")" "Accepts feat:"
assert_accepted "$(run_msg "fix(auth): handle missing token")" "Accepts fix(scope):"
assert_accepted "$(run_msg "chore: bump deps")" "Accepts chore:"
assert_accepted "$(run_msg "refactor(api): simplify error handling")" "Accepts refactor(scope):"

assert_rejected "$(run_msg "added user login")" "Rejects non-conventional subject"
assert_rejected "$(run_msg "FEAT: shouting type")" "Rejects uppercase type"
assert_rejected "$(run_msg "feat: Capitalized description")" "Rejects capitalized description"
assert_rejected "$(run_msg "wibble: unknown type")" "Rejects unknown type"

# Minimum length.
assert_rejected "$(run_msg "feat: x")" "Rejects too-short subject"

# Merge commits get a pass.
assert_accepted "$(run_msg "Merge branch 'main' into feature-x")" "Allows Merge commits"
assert_accepted "$(run_msg "merge pull request from origin")" "Allows merge (lowercase)"

# ---------------------------------------------------------------------------

test_suite "commit-msg: emoji detection"

# Emoji strings built via printf so this test file stays glyph-free.
ROCKET=$(printf '\xF0\x9F\x9A\x80')
PARTY=$(printf '\xF0\x9F\x8E\x89')

assert_rejected "$(run_msg "feat: ship it ${ROCKET}")" "Blocks rocket emoji in subject"
assert_rejected "$(run_msg "feat: real subject

body has ${PARTY} party emoji")" "Blocks emoji in body"

# Comment lines are stripped before evaluation; they never reach the check.
assert_accepted "$(run_msg "feat: clean subject
# this comment has ${ROCKET} but is stripped
real body")" "Strips '#' comment lines (git convention)"

# ---------------------------------------------------------------------------

print_test_summary
