#!/usr/bin/env bash
# Tests for claude-code/hooks/pre-commit-validate.sh
# Covers:
#   1. AI tool attribution detection (phrase-based, not bare tool names)
#   2. Co-authoring tag detection
#   3. Emoji detection
#   4. Conventional commit format validation
#   5. Minimum message length

set +e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOK="$DOTFILES_DIR/claude-code/hooks/pre-commit-validate.sh"

source "$SCRIPT_DIR/test-framework.sh"

# Helper: simulate a git commit -m through the hook
# Returns "denied", "ask", or "allowed"
run_commit_hook() {
    local msg="$1"
    local cmd="git commit -m \"$msg\""
    local json
    json=$(jq -n -c --arg cmd "$cmd" '{"tool_name":"Bash","tool_input":{"command":$cmd}}')
    local result
    result=$(echo "$json" | bash "$HOOK" 2>/dev/null)
    if [[ -z "$result" ]]; then
        echo "allowed"
    elif echo "$result" | jq -r '.hookSpecificOutput.permissionDecision' 2>/dev/null | grep -q "deny"; then
        echo "denied"
    elif echo "$result" | jq -r '.hookSpecificOutput.permissionDecision' 2>/dev/null | grep -q "ask"; then
        echo "ask"
    else
        echo "unknown"
    fi
}

# Helper: simulate a heredoc commit through the hook
run_commit_hook_heredoc() {
    local msg="$1"
    local cmd
    cmd="git commit -m \"\$(cat <<'EOF'
$msg
EOF
)\""
    local json
    json=$(jq -n -c --arg cmd "$cmd" '{"tool_name":"Bash","tool_input":{"command":$cmd}}')
    local result
    result=$(echo "$json" | bash "$HOOK" 2>/dev/null)
    if [[ -z "$result" ]]; then
        echo "allowed"
    elif echo "$result" | jq -r '.hookSpecificOutput.permissionDecision' 2>/dev/null | grep -q "deny"; then
        echo "denied"
    elif echo "$result" | jq -r '.hookSpecificOutput.permissionDecision' 2>/dev/null | grep -q "ask"; then
        echo "ask"
    else
        echo "unknown"
    fi
}

assert_denied() {
    local result="$1" label="$2"
    if [[ "$result" == "denied" ]]; then
        test_pass "$label"
    else
        test_fail "$label (expected denied, got $result)"
    fi
}

assert_allowed() {
    local result="$1" label="$2"
    if [[ "$result" == "allowed" ]]; then
        test_pass "$label"
    else
        test_fail "$label (expected allowed, got $result)"
    fi
}

assert_ask() {
    local result="$1" label="$2"
    if [[ "$result" == "ask" ]]; then
        test_pass "$label"
    else
        test_fail "$label (expected ask, got $result)"
    fi
}

#
# Test Suite: AI Attribution Detection
#

test_suite "AI Attribution -- Should Block"

assert_denied "$(run_commit_hook 'feat: generated by Claude Code')" \
    "Blocks 'generated by Claude Code'"

assert_denied "$(run_commit_hook 'feat: written with Copilot assistance')" \
    "Blocks 'written with Copilot'"

assert_denied "$(run_commit_hook 'feat: GPT-4 generated this refactor')" \
    "Blocks 'GPT generated'"

assert_denied "$(run_commit_hook 'feat: powered by Claude for speed')" \
    "Blocks 'powered by Claude'"

assert_denied "$(run_commit_hook 'feat: ai-generated code cleanup')" \
    "Blocks 'ai-generated'"

assert_denied "$(run_commit_hook 'feat: AI generated refactoring pass')" \
    "Blocks 'AI generated'"

assert_denied "$(run_commit_hook 'feat: created with OpenAI tools')" \
    "Blocks 'created with OpenAI'"

assert_denied "$(run_commit_hook 'feat: built with Cursor AI features')" \
    "Blocks 'built with Cursor AI'"

assert_denied "$(run_commit_hook 'feat: check claude.com for details')" \
    "Blocks 'claude.com'"

assert_denied "$(run_commit_hook 'feat: see anthropic.com for docs')" \
    "Blocks 'anthropic.com'"

test_suite "AI Attribution -- Should Allow (Technical References)"

assert_allowed "$(run_commit_hook 'feat: add global config for code-completion CLI')" \
    "Allows generic tool description"

assert_allowed "$(run_commit_hook 'docs: deploy instructions to ~/.copilot/')" \
    "Allows copilot in file path"

assert_allowed "$(run_commit_hook 'feat: add copilot-instructions.md for IDE support')" \
    "Allows copilot in filename"

assert_allowed "$(run_commit_hook 'fix: update Claude Code configuration path')" \
    "Allows Claude Code in technical context"

assert_allowed "$(run_commit_hook 'chore: remove GPT-3 API endpoint from config')" \
    "Allows GPT in technical context"

assert_allowed "$(run_commit_hook 'feat: add Codex CLI workflow parity')" \
    "Allows Codex in technical context"

assert_allowed "$(run_commit_hook 'docs: document three-file git config model')" \
    "Allows normal commit message"

#
# Test Suite: Co-authoring Tags
#

test_suite "Co-authoring Tags"

assert_denied "$(run_commit_hook_heredoc 'feat: add feature

Co-Authored-By: Bot <bot@example.com>')" \
    "Blocks Co-Authored-By tag"

assert_denied "$(run_commit_hook_heredoc 'feat: add feature

co-authored by: someone')" \
    "Blocks co-authored by (lowercase)"

assert_allowed "$(run_commit_hook 'feat: refactor auth module for team')" \
    "Allows normal message without co-author tags"

#
# Test Suite: Conventional Commit Format
#

test_suite "Conventional Commit Format"

assert_allowed "$(run_commit_hook 'feat: add user authentication')" \
    "Allows valid feat commit"

assert_allowed "$(run_commit_hook 'fix(auth): resolve login timeout')" \
    "Allows valid fix with scope"

assert_allowed "$(run_commit_hook 'docs: update README with examples')" \
    "Allows valid docs commit"

assert_allowed "$(run_commit_hook 'refactor: simplify error handling')" \
    "Allows valid refactor commit"

assert_ask "$(run_commit_hook 'Add new feature')" \
    "Asks about missing conventional type"

assert_ask "$(run_commit_hook 'feat: A')" \
    "Asks about too-short message"

assert_ask "$(run_commit_hook 'feat: Add with uppercase description')" \
    "Asks about uppercase description start"

assert_ask "$(run_commit_hook 'invalid: not a real type')" \
    "Asks about invalid commit type"

#
# Test Suite: Non-commit Commands (should pass through)
#

test_suite "Non-commit Commands"

result=$(echo '{"tool_name":"Bash","tool_input":{"command":"git status"}}' | bash "$HOOK" 2>/dev/null)
if [[ -z "$result" ]]; then
    test_pass "Passes through non-commit git commands"
else
    test_fail "Should not validate non-commit commands"
fi

result=$(echo '{"tool_name":"Read","tool_input":{"file_path":"/tmp/test"}}' | bash "$HOOK" 2>/dev/null)
if [[ -z "$result" ]]; then
    test_pass "Passes through non-Bash tools"
else
    test_fail "Should not validate non-Bash tools"
fi

#
# Results
#

echo ""
print_test_summary
