#!/usr/bin/env bash
# Shared detection patterns for commit validation and content hooks.
# Sourced by pre-code-no-emoji.sh and git/hooks/commit-msg.
# Not executable on its own.

# Attribution detection: returns 0 if text contains AI tool attribution.
# Matches attribution phrases ("generated by", "written with") near tool names.
# The tool name and the participle must be adjacent (at most one word apart),
# and the name itself must be bounded by non-letters. A plain `.*` between them
# matched any co-occurrence -- "~/.claude/settings.json ... regenerated" tripped
# it -- and an unbounded `ai` matched inside words like "maintenance".
# Does NOT match bare tool names in file paths or technical references.
has_ai_attribution() {
    local text="$1"
    echo "$text" | grep -qiE '(generated (with|by)|powered by|created (with|by)|written (with|by)|assisted by|produced by|authored by|built with|made with).*(^|[^[:alpha:]])(claude|anthropic|gpt|openai|copilot|gemini|cursor|windsurf|ai)([^[:alpha:]]|$)' ||
    echo "$text" | grep -qiE '(^|[^[:alpha:]])(claude|anthropic|gpt|openai|copilot|gemini|cursor|windsurf|ai)[ _-]*([[:alpha:]]+[ _-]+)?(generated|powered|created|wrote|assisted|produced|authored|built)([^[:alpha:]]|$)' ||
    echo "$text" | grep -qiE '(claude\.com|anthropic\.com|ai-generated|ai generated)'
}

# Co-authoring tag detection: returns 0 if text contains co-author tags.
has_coauthor_tag() {
    local text="$1"
    echo "$text" | grep -qiE 'co-authored-by:|co-authored by:'
}

# Emoji detection: returns 0 if text contains decorative emoji characters.
# Uses perl for portability (grep -P unavailable on macOS).
# Covers: Emoticons, Symbols, Pictographs, Transport, Flags, variation selectors.
has_emoji() {
    local text="$1"
    echo "$text" | perl -CSD -ne \
        'BEGIN{$f=1} if(/[\x{1F000}-\x{1FAFF}\x{2300}-\x{23FF}\x{2600}-\x{27BF}\x{2B50}\x{2B55}\x{FE00}-\x{FE0F}\x{200D}]/){$f=0} END{exit $f}'
}

# Markdown task symbols that should NOT be flagged as emoji.
ALLOWED_TASK_SYMBOLS='☐☑✓✗□■▪▫✔✘'

# Strip allowed task symbols from text before emoji checking.
# Usage: filtered=$(strip_allowed_symbols "$text")
strip_allowed_symbols() {
    local text="$1"
    # shellcheck disable=SC2001  # can't use ${//} with character class from variable
    echo "$text" | sed "s/[$ALLOWED_TASK_SYMBOLS]//g"
}
